version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: imageboard-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: imageboard-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: imageboard
      POSTGRES_PASSWORD: imageboard
      POSTGRES_DB: imageboard
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: imageboard-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data: